### PR TITLE
Fixed typo in name of GNU General Public License

### PR DESCRIPTION
**Pull request by marctjones**
Fixed the name of the "GNU General Public License." It was missing the word "General"

A similar PR may already be submitted!
Please search among the [Pull request](../) before creating one.

Thanks for submitting a pull request! Please provide enough information so that others can review your pull request:

For more information, see the `CONTRIBUTING` guide.

**Summary**

This PR fixes/implements the following **bugs/features**

* Fixes a typo in the name of the GNU General Public License

Explain the **motivation** for making this change. What existing problem does the pull request solve?

**Test plan (required)**
No tests required. Just fixing a typo

**Code formatting**
Just fixing a typo. So not affecting code format

**Closing issues**
No open issues for this that I saw.

### CODE REVIEW

**Comment by marctjones** [comment]
Fixing a typo in the name of GNU General Public License. It is missing the word General on the licensing information section.

**Comment by DanielJDufour** [comment]
Awesome.  Looks good.  As soon as the tests pass, I'll merge!

**Comment by DanielJDufour** [comment]
Tests passed.  I inspected circle ci logs manually.  Test job failed though because we haven't set up code climate to run on forks.  Accepting and merging now.

**Comment by DanielJDufour** [comment]
Thanks @marctjones !

**Pull request merged**
